# Generated by Django 4.1.7 on 2024-01-06 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, verbose_name='Userame')),
                ('email', models.EmailField(max_length=50, verbose_name='User Email')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('photo', models.ImageField(null=True, upload_to='pfps/')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('incoming', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='core.users')),
                ('outgoing', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25, verbose_name='Group name')),
                ('members', models.ManyToManyField(to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('incoming', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='gincoming', to='core.groups')),
                ('outgoing', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='goutgoing', to='core.users')),
            ],
        ),
    ]
