# Generated by Django 4.1.7 on 2024-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='admin',
            field=models.ManyToManyField(related_name='admin', to='core.users'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='members', to='core.users'),
        ),
    ]
