# Generated by Django 4.1.7 on 2024-01-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groups_admin_alter_groups_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='photo',
            field=models.ImageField(null=True, upload_to='pfps/'),
        ),
    ]
