# Generated by Django 4.1.7 on 2024-02-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groups_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInstances',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='type',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='message',
        ),
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.ManyToManyField(related_name='messages', to='core.messageinstances'),
        ),
    ]
