# Generated by Django 4.1.7 on 2024-02-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_messageinstances_remove_messages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmessages', to='core.messageinstances'),
        ),
        migrations.RemoveField(
            model_name='messages',
            name='message',
        ),
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='directmessages', to='core.messageinstances'),
            preserve_default=False,
        ),
    ]
