# Generated by Django 4.1.7 on 2024-02-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_groupmessage_message_remove_messages_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageinstances',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
