# Generated by Django 4.1.7 on 2024-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_messageinstances_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageinstances',
            name='date_time',
        ),
        migrations.AddField(
            model_name='messageinstances',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageinstances',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
