# Generated by Django 4.1.7 on 2024-02-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_messageinstances_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='type',
        ),
    ]
