# Generated by Django 4.1.7 on 2023-09-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_users_photo_users_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='title',
        ),
    ]
