# Generated by Django 4.1.7 on 2023-09-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_users_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='pfps/'),
        ),
    ]
