# Generated by Django 4.1.7 on 2023-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_users_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('incoming', models.TextField(max_length=20)),
                ('outgoing', models.TextField(max_length=20)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
