# Generated by Django 4.1.7 on 2023-09-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_alter_messages_incoming_alter_messages_outgoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='incoming',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='outgoing',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.messages'),
        ),
    ]
