# Generated by Django 4.1.7 on 2023-09-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_alter_messages_incoming_alter_messages_outgoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='signup.messages'),
        ),
    ]
