# Generated by Django 4.1.7 on 2023-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_alter_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AlterField(
            model_name='messages',
            name='incoming',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='outgoing',
            field=models.TextField(max_length=20),
        ),
    ]
