# Generated by Django 4.1.7 on 2023-09-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_users_user_alter_messages_incoming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AlterField(
            model_name='messages',
            name='incoming',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='signup.users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='outgoing',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='signup.users'),
        ),
    ]
