# Generated by Django 4.0.6 on 2023-10-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_remove_users_user_alter_messages_incoming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='type',
            field=models.CharField(max_length=10, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
