# Generated by Django 4.1.7 on 2023-09-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_messages_image_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
